name: Application Deployment

on:
  workflow_dispatch:

jobs:
  helm-deploy-app:
    name: Deploy Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Get AKS credentials
        run: az aks get-credentials --resource-group ${{ secrets.AKS_RESOURCE_GROUP }} --name ${{ secrets.AKS_CLUSTER_NAME }}

        # Add the sleep command here to wait for SecretProviderClass to be ready
      - name: Wait for Secrets Provider
        run: sleep 10 
        
      - name: Deploy using Helm
        run: |
          helm upgrade --install relianceapp ./helm-charts/reliance-app \
            --namespace staging \
            --values ./helm-charts/reliance-app/values-staging.yaml
