name: Infrastructure Configuration

on:
  workflow_dispatch:   # Allow manual trigger from Actions UI
              
jobs:
  helm-config-infra:
    name: Deploy to AKS via Helm
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
  
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
  
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
  
      - name: Set up Helm
        uses: azure/setup-helm@v3
  
      - name: Get AKS credentials
        run: az aks get-credentials --resource-group ${{ secrets.AKS_RESOURCE_GROUP }} --name ${{ secrets.AKS_CLUSTER_NAME }}
  
      - name: Create 'staging' namespace if not exists
        run: |
          kubectl create namespace staging --dry-run=client -o yaml | kubectl apply -f -
      - name: Install Secrets Store CSI Driver and Azure Provider
        run: |
          # Add the repository for the core Secrets Store CSI Driver
          helm repo add secrets-store-csi-driver https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts
          helm repo update
          # Clean up any existing CSI driver installations to prevent conflicts
          helm uninstall csi-secrets-store-driver --namespace kube-system --ignore-not-found
          # Deploy the core CSI driver and enable the Azure provider in one command
          helm upgrade --install csi-secrets-store-driver secrets-store-csi-driver/secrets-store-csi-driver \
            --namespace kube-system \
            --set "providers.azure.enabled=true"
  
      - name: Install NGINX Ingress Controller
        run: |
          # Add the repository for NGINX Ingress Controller
          helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
          helm repo update
          # Clean up any existing NGINX Ingress installations to prevent conflicts
          helm uninstall ingress-nginx --namespace ingress-nginx --ignore-not-found
          # Deploy the NGINX Ingress Controller
          helm upgrade --install ingress-nginx ingress-nginx/ingress-nginx \
            --namespace ingress-nginx --create-namespace
